// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOg0ZL6VqcvXZYhuBW2EbyfhIsOse8xvE',
    appId: '1:943743213313:web:20f229605af4f02ca7c500',
    messagingSenderId: '943743213313',
    projectId: 'focusflow-b92c6',
    authDomain: 'focusflow-b92c6.firebaseapp.com',
    storageBucket: 'focusflow-b92c6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFp5ACLH5cs0qpd_76Z_jlB_4Dgf-I0nQ',
    appId: '1:943743213313:android:47439f477d04ebd1a7c500',
    messagingSenderId: '943743213313',
    projectId: 'focusflow-b92c6',
    storageBucket: 'focusflow-b92c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjqlT8ueOT9f-I84iICZ4lhb8CCl4vgKY',
    appId: '1:943743213313:ios:4e3b9882781f3042a7c500',
    messagingSenderId: '943743213313',
    projectId: 'focusflow-b92c6',
    storageBucket: 'focusflow-b92c6.firebasestorage.app',
    iosBundleId: 'com.example.focusflow.app',
  );
}
